name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'TopchetoEU'
          repository: 'java-jscript'
      - name: "Build"
        run: |
          ls -R; cd java-jscript; node ./build.js release ${{ github.ref }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            java-jscript/LICENSE
            java-jscript/dst/*.jar